//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OnlyTestMsg.proto
namespace com.road.pitaya.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestMsg")]
  public partial class TestMsg : global::ProtoBuf.IExtensible
  {
    public TestMsg() {}
    
    private int _f1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"f1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int f1
    {
      get { return _f1; }
      set { _f1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}