// Generated by the protocol buffer compiler.  DO NOT EDIT!

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
public static partial class ProtoMyData {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_MyData__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::MyData, global::MyData.Builder> internal__static_MyData__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static ProtoMyData() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        "ChFQcm90b015RGF0YS5wcm90byIlCgZNeURhdGESGwoGcmVzdW1lGAEgASgJ" + 
        "OgtJJ20gZ29vZG1hbg==");
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_MyData__Descriptor = Descriptor.MessageTypes[0];
      internal__static_MyData__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::MyData, global::MyData.Builder>(internal__static_MyData__Descriptor,
              new string[] { "Resume", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
public sealed partial class MyData : pb::GeneratedMessage<MyData, MyData.Builder> {
  private static readonly MyData defaultInstance = new Builder().BuildPartial();
  public static MyData DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override MyData DefaultInstanceForType {
    get { return defaultInstance; }
  }
  
  protected override MyData ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ProtoMyData.internal__static_MyData__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<MyData, MyData.Builder> InternalFieldAccessors {
    get { return global::ProtoMyData.internal__static_MyData__FieldAccessorTable; }
  }
  
  public const int ResumeFieldNumber = 1;
  private bool hasResume;
  private string resume_ = "I\'m goodman";
  public bool HasResume {
    get { return hasResume; }
  }
  public string Resume {
    get { return resume_; }
  }
  
  public override bool IsInitialized {
    get {
      return true;
    }
  }
  
  public override void WriteTo(pb::CodedOutputStream output) {
    int size = SerializedSize;
    if (HasResume) {
      output.WriteString(1, Resume);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (HasResume) {
        size += pb::CodedOutputStream.ComputeStringSize(1, Resume);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static MyData ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyData ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyData ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyData ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyData ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyData ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static MyData ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static MyData ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static MyData ParseFrom(pb::CodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyData ParseFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(MyData prototype) {
    return (Builder) new Builder().MergeFrom(prototype);
  }
  
  public sealed partial class Builder : pb::GeneratedBuilder<MyData, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {}
    
    MyData result = new MyData();
    
    protected override MyData MessageBeingBuilt {
      get { return result; }
    }
    
    public override Builder Clear() {
      result = new MyData();
      return this;
    }
    
    public override Builder Clone() {
      return new Builder().MergeFrom(result);
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::MyData.Descriptor; }
    }
    
    public override MyData DefaultInstanceForType {
      get { return global::MyData.DefaultInstance; }
    }
    
    public override MyData BuildPartial() {
      if (result == null) {
        throw new global::System.InvalidOperationException("build() has already been called on this Builder");
      }
      MyData returnMe = result;
      result = null;
      return returnMe;
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is MyData) {
        return MergeFrom((MyData) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(MyData other) {
      if (other == global::MyData.DefaultInstance) return this;
      if (other.HasResume) {
        Resume = other.Resume;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      pb::UnknownFieldSet.Builder unknownFields = null;
      while (true) {
        uint tag = input.ReadTag();
        switch (tag) {
          case 0: {
            if (unknownFields != null) {
              this.UnknownFields = unknownFields.Build();
            }
            return this;
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag);
            break;
          }
          case 10: {
            Resume = input.ReadString();
            break;
          }
        }
      }
    }
    
    
    public bool HasResume {
      get { return result.HasResume; }
    }
    public string Resume {
      get { return result.Resume; }
      set { SetResume(value); }
    }
    public Builder SetResume(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.hasResume = true;
      result.resume_ = value;
      return this;
    }
    public Builder ClearResume() {
      result.hasResume = false;
      result.resume_ = "I\'m goodman";
      return this;
    }
  }
  static MyData() {
    object.ReferenceEquals(global::ProtoMyData.Descriptor, null);
  }
}

#endregion

