// Generated by the protocol buffer compiler.  DO NOT EDIT!

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
public static partial class ProtoMyResponse {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_MyResponse__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::MyResponse, global::MyResponse.Builder> internal__static_MyResponse__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static ProtoMyResponse() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        "ChVQcm90b015UmVzcG9uc2UucHJvdG8iLQoKTXlSZXNwb25zZRIPCgd2ZXJz" + 
        "aW9uGAEgAigFEg4KBnJlc3VsdBgCIAIoBQ==");
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_MyResponse__Descriptor = Descriptor.MessageTypes[0];
      internal__static_MyResponse__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::MyResponse, global::MyResponse.Builder>(internal__static_MyResponse__Descriptor,
              new string[] { "Version", "Result", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
public sealed partial class MyResponse : pb::GeneratedMessage<MyResponse, MyResponse.Builder> {
  private static readonly MyResponse defaultInstance = new Builder().BuildPartial();
  public static MyResponse DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override MyResponse DefaultInstanceForType {
    get { return defaultInstance; }
  }
  
  protected override MyResponse ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ProtoMyResponse.internal__static_MyResponse__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<MyResponse, MyResponse.Builder> InternalFieldAccessors {
    get { return global::ProtoMyResponse.internal__static_MyResponse__FieldAccessorTable; }
  }
  
  public const int VersionFieldNumber = 1;
  private bool hasVersion;
  private int version_ = 0;
  public bool HasVersion {
    get { return hasVersion; }
  }
  public int Version {
    get { return version_; }
  }
  
  public const int ResultFieldNumber = 2;
  private bool hasResult;
  private int result_ = 0;
  public bool HasResult {
    get { return hasResult; }
  }
  public int Result {
    get { return result_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasVersion) return false;
      if (!hasResult) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::CodedOutputStream output) {
    int size = SerializedSize;
    if (HasVersion) {
      output.WriteInt32(1, Version);
    }
    if (HasResult) {
      output.WriteInt32(2, Result);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (HasVersion) {
        size += pb::CodedOutputStream.ComputeInt32Size(1, Version);
      }
      if (HasResult) {
        size += pb::CodedOutputStream.ComputeInt32Size(2, Result);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static MyResponse ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyResponse ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyResponse ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static MyResponse ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static MyResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static MyResponse ParseFrom(pb::CodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyResponse ParseFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(MyResponse prototype) {
    return (Builder) new Builder().MergeFrom(prototype);
  }
  
  public sealed partial class Builder : pb::GeneratedBuilder<MyResponse, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {}
    
    MyResponse result = new MyResponse();
    
    protected override MyResponse MessageBeingBuilt {
      get { return result; }
    }
    
    public override Builder Clear() {
      result = new MyResponse();
      return this;
    }
    
    public override Builder Clone() {
      return new Builder().MergeFrom(result);
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::MyResponse.Descriptor; }
    }
    
    public override MyResponse DefaultInstanceForType {
      get { return global::MyResponse.DefaultInstance; }
    }
    
    public override MyResponse BuildPartial() {
      if (result == null) {
        throw new global::System.InvalidOperationException("build() has already been called on this Builder");
      }
      MyResponse returnMe = result;
      result = null;
      return returnMe;
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is MyResponse) {
        return MergeFrom((MyResponse) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(MyResponse other) {
      if (other == global::MyResponse.DefaultInstance) return this;
      if (other.HasVersion) {
        Version = other.Version;
      }
      if (other.HasResult) {
        Result = other.Result;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      pb::UnknownFieldSet.Builder unknownFields = null;
      while (true) {
        uint tag = input.ReadTag();
        switch (tag) {
          case 0: {
            if (unknownFields != null) {
              this.UnknownFields = unknownFields.Build();
            }
            return this;
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag);
            break;
          }
          case 8: {
            Version = input.ReadInt32();
            break;
          }
          case 16: {
            Result = input.ReadInt32();
            break;
          }
        }
      }
    }
    
    
    public bool HasVersion {
      get { return result.HasVersion; }
    }
    public int Version {
      get { return result.Version; }
      set { SetVersion(value); }
    }
    public Builder SetVersion(int value) {
      result.hasVersion = true;
      result.version_ = value;
      return this;
    }
    public Builder ClearVersion() {
      result.hasVersion = false;
      result.version_ = 0;
      return this;
    }
    
    public bool HasResult {
      get { return result.HasResult; }
    }
    public int Result {
      get { return result.Result; }
      set { SetResult(value); }
    }
    public Builder SetResult(int value) {
      result.hasResult = true;
      result.result_ = value;
      return this;
    }
    public Builder ClearResult() {
      result.hasResult = false;
      result.result_ = 0;
      return this;
    }
  }
  static MyResponse() {
    object.ReferenceEquals(global::ProtoMyResponse.Descriptor, null);
  }
}

#endregion

