// Generated by the protocol buffer compiler.  DO NOT EDIT!

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
public static partial class ProtoMyRequest {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_MyRequest__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::MyRequest, global::MyRequest.Builder> internal__static_MyRequest__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static ProtoMyRequest() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        "ChRQcm90b015UmVxdWVzdC5wcm90byJiCglNeVJlcXVlc3QSDwoHdmVyc2lv" + 
        "bhgBIAIoBRIMCgRuYW1lGAIgAigJEigKB3dlYnNpdGUYAyABKAk6F2h0dHA6" + 
        "Ly93d3cucGFvdGlhby5jb20vEgwKBGRhdGEYBCABKAw=");
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_MyRequest__Descriptor = Descriptor.MessageTypes[0];
      internal__static_MyRequest__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::MyRequest, global::MyRequest.Builder>(internal__static_MyRequest__Descriptor,
              new string[] { "Version", "Name", "Website", "Data", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
public sealed partial class MyRequest : pb::GeneratedMessage<MyRequest, MyRequest.Builder> {
  private static readonly MyRequest defaultInstance = new Builder().BuildPartial();
  public static MyRequest DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override MyRequest DefaultInstanceForType {
    get { return defaultInstance; }
  }
  
  protected override MyRequest ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ProtoMyRequest.internal__static_MyRequest__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<MyRequest, MyRequest.Builder> InternalFieldAccessors {
    get { return global::ProtoMyRequest.internal__static_MyRequest__FieldAccessorTable; }
  }
  
  public const int VersionFieldNumber = 1;
  private bool hasVersion;
  private int version_ = 0;
  public bool HasVersion {
    get { return hasVersion; }
  }
  public int Version {
    get { return version_; }
  }
  
  public const int NameFieldNumber = 2;
  private bool hasName;
  private string name_ = "";
  public bool HasName {
    get { return hasName; }
  }
  public string Name {
    get { return name_; }
  }
  
  public const int WebsiteFieldNumber = 3;
  private bool hasWebsite;
  private string website_ = "http://www.paotiao.com/";
  public bool HasWebsite {
    get { return hasWebsite; }
  }
  public string Website {
    get { return website_; }
  }
  
  public const int DataFieldNumber = 4;
  private bool hasData;
  private pb::ByteString data_ = pb::ByteString.Empty;
  public bool HasData {
    get { return hasData; }
  }
  public pb::ByteString Data {
    get { return data_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasVersion) return false;
      if (!hasName) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::CodedOutputStream output) {
    int size = SerializedSize;
    if (HasVersion) {
      output.WriteInt32(1, Version);
    }
    if (HasName) {
      output.WriteString(2, Name);
    }
    if (HasWebsite) {
      output.WriteString(3, Website);
    }
    if (HasData) {
      output.WriteBytes(4, Data);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (HasVersion) {
        size += pb::CodedOutputStream.ComputeInt32Size(1, Version);
      }
      if (HasName) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Name);
      }
      if (HasWebsite) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Website);
      }
      if (HasData) {
        size += pb::CodedOutputStream.ComputeBytesSize(4, Data);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static MyRequest ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyRequest ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static MyRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static MyRequest ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static MyRequest ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static MyRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static MyRequest ParseFrom(pb::CodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static MyRequest ParseFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(MyRequest prototype) {
    return (Builder) new Builder().MergeFrom(prototype);
  }
  
  public sealed partial class Builder : pb::GeneratedBuilder<MyRequest, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {}
    
    MyRequest result = new MyRequest();
    
    protected override MyRequest MessageBeingBuilt {
      get { return result; }
    }
    
    public override Builder Clear() {
      result = new MyRequest();
      return this;
    }
    
    public override Builder Clone() {
      return new Builder().MergeFrom(result);
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::MyRequest.Descriptor; }
    }
    
    public override MyRequest DefaultInstanceForType {
      get { return global::MyRequest.DefaultInstance; }
    }
    
    public override MyRequest BuildPartial() {
      if (result == null) {
        throw new global::System.InvalidOperationException("build() has already been called on this Builder");
      }
      MyRequest returnMe = result;
      result = null;
      return returnMe;
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is MyRequest) {
        return MergeFrom((MyRequest) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(MyRequest other) {
      if (other == global::MyRequest.DefaultInstance) return this;
      if (other.HasVersion) {
        Version = other.Version;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasWebsite) {
        Website = other.Website;
      }
      if (other.HasData) {
        Data = other.Data;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::CodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      pb::UnknownFieldSet.Builder unknownFields = null;
      while (true) {
        uint tag = input.ReadTag();
        switch (tag) {
          case 0: {
            if (unknownFields != null) {
              this.UnknownFields = unknownFields.Build();
            }
            return this;
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag);
            break;
          }
          case 8: {
            Version = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Website = input.ReadString();
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    
    
    public bool HasVersion {
      get { return result.HasVersion; }
    }
    public int Version {
      get { return result.Version; }
      set { SetVersion(value); }
    }
    public Builder SetVersion(int value) {
      result.hasVersion = true;
      result.version_ = value;
      return this;
    }
    public Builder ClearVersion() {
      result.hasVersion = false;
      result.version_ = 0;
      return this;
    }
    
    public bool HasName {
      get { return result.HasName; }
    }
    public string Name {
      get { return result.Name; }
      set { SetName(value); }
    }
    public Builder SetName(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.hasName = true;
      result.name_ = value;
      return this;
    }
    public Builder ClearName() {
      result.hasName = false;
      result.name_ = "";
      return this;
    }
    
    public bool HasWebsite {
      get { return result.HasWebsite; }
    }
    public string Website {
      get { return result.Website; }
      set { SetWebsite(value); }
    }
    public Builder SetWebsite(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.hasWebsite = true;
      result.website_ = value;
      return this;
    }
    public Builder ClearWebsite() {
      result.hasWebsite = false;
      result.website_ = "http://www.paotiao.com/";
      return this;
    }
    
    public bool HasData {
      get { return result.HasData; }
    }
    public pb::ByteString Data {
      get { return result.Data; }
      set { SetData(value); }
    }
    public Builder SetData(pb::ByteString value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      result.hasData = true;
      result.data_ = value;
      return this;
    }
    public Builder ClearData() {
      result.hasData = false;
      result.data_ = pb::ByteString.Empty;
      return this;
    }
  }
  static MyRequest() {
    object.ReferenceEquals(global::ProtoMyRequest.Descriptor, null);
  }
}

#endregion

